#!/usr/bin/env python3
"""Render the paper's synthetic-benchmark tables from ``results/synthetic_benchmark/summary.json``.

Every number in ``paper/tables/*.tex`` is produced here from the committed
benchmark summary, with the same rounding as ``summary.md``; nothing is typed
by hand.  ``--check`` exits non-zero when the committed tables are stale
(``tests/test_paper_tables.py`` runs the same comparison).

Usage (from the repository root)::

    python projects/llm-factor-mining/scripts/render_paper_tables.py          # write
    python projects/llm-factor-mining/scripts/render_paper_tables.py --check  # verify

All values describe synthetic data only.
"""

from __future__ import annotations

import argparse
from collections.abc import Mapping, Sequence
import json
from pathlib import Path
import sys
from typing import Any


PROJECT = Path(__file__).resolve().parents[1]
SUMMARY = PROJECT / "results" / "synthetic_benchmark" / "summary.json"
TABLE_DIR = PROJECT / "paper" / "tables"
HEADER = (
    "% Generated by scripts/render_paper_tables.py from results/synthetic_benchmark/summary.json.\n"
    "% Do not edit by hand. SYNTHETIC DATA - NOT EVIDENCE ABOUT REAL MARKETS.\n"
)


def fmt(value: Any, digits: int) -> str:
    """Same rounding as ``llm_factor_mining.benchmark.report``; ``n/a`` for missing values."""

    if value is None:
        return "n/a"
    return f"{float(value):.{digits}f}"


def mean_sd(stats: Mapping[str, Any], digits: int) -> str:
    """``mean $\\pm$ sd`` (``mean`` alone when the sd is undefined)."""

    if not stats or stats.get("mean") is None:
        return "n/a"
    mean = fmt(stats["mean"], digits)
    sd = stats.get("std")
    return mean if sd is None else f"{mean} $\\pm$ {fmt(sd, digits)}"


def latex_scientific(value: float) -> str:
    """``2.8e-13`` -> ``$2.8\\times10^{-13}$``."""

    mantissa, exponent = f"{float(value):.1e}".split("e")
    return f"${mantissa}\\times10^{{{int(exponent)}}}$"


def tex_name(name: str) -> str:
    return "\\texttt{" + name.replace("_", "\\_") + "}"


def _rows(lines: Sequence[str]) -> str:
    return "".join(f"{line} \\\\\n" for line in lines)


def _planted_markets(summary: Mapping[str, Any]) -> list[Mapping[str, Any]]:
    return [market for market in summary["markets"] if float(market["snr"]) > 0]


def headline_table(summary: Mapping[str, Any]) -> str:
    lines = []
    for row in summary["aggregate"]:
        m = row["metrics"]
        cells = [
            fmt(row["snr"], 2),
            row["arm"],
            f"{row['n_complete']}/{row['n_runs']}",
            mean_sd(m["recovery_rate"], 2),
            mean_sd(m["recall_rate"], 2),
            mean_sd(m["n_selected"], 1),
            mean_sd(m["fdp_true"], 2),
            mean_sd(m["test_nonsignificant_rate"], 2),
            mean_sd(m["composite_test_ic"], 4),
            mean_sd(m["composite_test_icir"], 3),
            mean_sd(m["behavioural_novelty_mean"], 2),
            mean_sd(m["structural_novelty_mean"], 2),
        ]
        lines.append(" & ".join(cells))
    return (
        HEADER
        + "\\begin{tabular}{llcccccccccc}\n\\toprule\n"
        + "SNR & Arm & Complete & Recovery & Recall & Selected & True FDP & Test non-sig. "
        + "& Composite test IC & Composite test ICIR & Behav. novelty & Struct. novelty \\\\\n\\midrule\n"
        + _rows(lines)
        + "\\bottomrule\n\\end{tabular}\n"
    )


def recovery_table(summary: Mapping[str, Any]) -> str:
    planted = [item["name"] for item in summary["planted"]]
    lines = []
    for row in summary["aggregate"]:
        n = row["n_complete"]
        cells = [fmt(row["snr"], 2), row["arm"]]
        cells += [
            f"{row['recovered_counts'].get(name, 0)}/{n} selected, {row['recalled_counts'].get(name, 0)}/{n} found"
            for name in planted
        ]
        lines.append(" & ".join(cells))
    return (
        HEADER
        + "\\begin{tabular}{ll" + "c" * len(planted) + "}\n\\toprule\n"
        + "SNR & Arm & " + " & ".join(tex_name(name) for name in planted) + " \\\\\n\\midrule\n"
        + _rows(lines)
        + "\\bottomrule\n\\end{tabular}\n"
    )


def _span(values: Sequence[Any], digits: int) -> str:
    finite = [float(value) for value in values if value is not None]
    if not finite:
        return "n/a"
    low, high = fmt(min(finite), digits), fmt(max(finite), digits)
    return low if low == high else f"{low} to {high}"


def null_cells(summary: Mapping[str, Any]) -> list[list[str]]:
    """Cells of the null-market table (same content as ``summary.md``)."""

    runs = [run for run in summary["runs"] if float(run["snr"]) == 0 and run.get("complete")]
    rows = []
    for row in summary.get("null_aggregate", []):
        m = row["metrics"]
        mine = [run for run in runs if run["arm"] == row["arm"]]
        selecting = sum(1 for run in mine if run.get("n_selected"))
        composite_t = [(run.get("composite_test") or {}).get("t_nw") for run in mine if run.get("n_selected")]
        rows.append(
            [
                row["arm"],
                f"{row['n_complete']}/{row['n_runs']}",
                f"{selecting}/{row['n_complete']}",
                mean_sd(m["n_selected"], 1),
                mean_sd(m["n_screen_survivors"], 1),
                mean_sd(m["n_confirmed"], 1),
                _span(composite_t, 2),
            ]
        )
    return rows


def null_table(summary: Mapping[str, Any]) -> str:
    lines = [" & ".join(cells) for cells in null_cells(summary)]
    return (
        HEADER
        + "\\begin{tabular}{lcccccc}\n\\toprule\n"
        + "Arm & Complete & Runs selecting $\\geq 1$ & Selected & Screen survivors & Confirmed "
        + "& Composite test $t$ \\\\\n\\midrule\n"
        + _rows(lines)
        + "\\bottomrule\n\\end{tabular}\n"
    )


def oracle_table(summary: Mapping[str, Any]) -> str:
    planted = [item["name"] for item in summary["planted"]]
    lines = []
    for market in _planted_markets(summary):
        oracle = market["oracle_test"]
        cells = [fmt(market["snr"], 2), str(market["seed"])]
        cells += [f"{fmt(oracle[name]['ic_mean'], 4)} ({fmt(oracle[name]['t_nw'], 2)})" for name in planted]
        composite = oracle["composite"]
        cells.append(f"{fmt(composite['ic_mean'], 4)} ({fmt(composite['t_nw'], 2)})")
        cells.append(fmt(oracle.get("power"), 2))
        lines.append(" & ".join(cells))
    return (
        HEADER
        + "\\begin{tabular}{ll" + "c" * (len(planted) + 2) + "}\n\\toprule\n"
        + "SNR & Seed & " + " & ".join(tex_name(name) for name in planted)
        + " & Planted composite & Power \\\\\n\\midrule\n"
        + _rows(lines)
        + "\\bottomrule\n\\end{tabular}\n"
    )


def _oracle_range(summary: Mapping[str, Any], snr: float) -> tuple[float, float]:
    values = [
        float(market["oracle_test"]["composite"]["ic_mean"])
        for market in summary["markets"]
        if float(market["snr"]) == float(snr)
    ]
    return min(values), max(values)


AGGREGATE_DIGITS: dict[str, int] = {
    "recovery_rate": 2,
    "recall_rate": 2,
    "fdp_true": 2,
    "test_nonsignificant_rate": 2,
    "any_selected": 2,
    "n_selected": 1,
    "n_screen_survivors": 1,
    "n_confirmed": 1,
    "n_behaviour_classes": 1,
    "n_behaviour_duplicates": 1,
    "n_degenerate": 1,
    "composite_test_ic": 4,
    "composite_test_icir": 3,
    "composite_test_t": 2,
    "selected_test_ic_mean": 4,
    "composite_test_ls_net_sharpe": 2,
    "validity_rate": 2,
    "behavioural_novelty_mean": 2,
    "structural_novelty_mean": 2,
}

LOOKUP_HELPERS = r"""\makeatletter
% \SynMean{<snr>}{<arm>}{<metric>} and \SynMeanSd{...}: planted-market cells across complete runs.
% \SynNullMean{<arm>}{<metric>}, \SynNullMeanSd{...} and \SynNullSelecting{<arm>}: null markets.
\newcommand{\SynMean}[3]{\ifcsname syn@mean@#1@#2@#3\endcsname\csname syn@mean@#1@#2@#3\endcsname\else\PackageError{synthetic}{no synthetic value #1/#2/#3}{}\fi}
\newcommand{\SynMeanSd}[3]{\ifcsname syn@msd@#1@#2@#3\endcsname\csname syn@msd@#1@#2@#3\endcsname\else\PackageError{synthetic}{no synthetic value #1/#2/#3}{}\fi}
\newcommand{\SynNullMean}[2]{\ifcsname syn@nullmean@#1@#2\endcsname\csname syn@nullmean@#1@#2\endcsname\else\PackageError{synthetic}{no null value #1/#2}{}\fi}
\newcommand{\SynNullMeanSd}[2]{\ifcsname syn@nullmsd@#1@#2\endcsname\csname syn@nullmsd@#1@#2\endcsname\else\PackageError{synthetic}{no null value #1/#2}{}\fi}
\newcommand{\SynNullSelecting}[1]{\ifcsname syn@nullsel@#1\endcsname\csname syn@nullsel@#1\endcsname\else\PackageError{synthetic}{no null arm #1}{}\fi}
\makeatother
"""


def aggregate_macros(summary: Mapping[str, Any]) -> list[str]:
    """``\\csname``-keyed definitions behind :data:`LOOKUP_HELPERS`."""

    lines = []
    for row in summary["aggregate"]:
        key = f"{fmt(row['snr'], 2)}@{row['arm']}"
        for metric, digits in AGGREGATE_DIGITS.items():
            stats = row["metrics"][metric]
            mean = "n/a" if stats.get("mean") is None else fmt(stats["mean"], digits)
            lines.append(f"\\expandafter\\def\\csname syn@mean@{key}@{metric}\\endcsname{{{mean}}}")
            lines.append(f"\\expandafter\\def\\csname syn@msd@{key}@{metric}\\endcsname{{{mean_sd(stats, digits)}}}")
    for row, cells in zip(summary.get("null_aggregate", []), null_cells(summary)):
        arm = row["arm"]
        for metric, digits in AGGREGATE_DIGITS.items():
            stats = row["metrics"][metric]
            mean = "n/a" if stats.get("mean") is None else fmt(stats["mean"], digits)
            lines.append(f"\\expandafter\\def\\csname syn@nullmean@{arm}@{metric}\\endcsname{{{mean}}}")
            lines.append(f"\\expandafter\\def\\csname syn@nullmsd@{arm}@{metric}\\endcsname{{{mean_sd(stats, digits)}}}")
        lines.append(f"\\expandafter\\def\\csname syn@nullsel@{arm}\\endcsname{{{cells[2]}}}")
    return lines


def _family_counts(summary: Mapping[str, Any], family: str) -> tuple[int, int]:
    names = [item["name"] for item in summary["planted"] if item["family"] == family]
    found = sum(row["recalled_counts"].get(name, 0) for row in summary["aggregate"] for name in names)
    selected = sum(row["recovered_counts"].get(name, 0) for row in summary["aggregate"] for name in names)
    return found, selected


def macros(summary: Mapping[str, Any]) -> str:
    """Scalar facts quoted in the paper's prose, as LaTeX macros."""

    config = summary["config"]
    snrs = [float(value) for value in config["snr_levels"]]
    if len(snrs) != 2:
        raise ValueError("the paper's prose assumes exactly two SNR levels")
    low, high = sorted(snrs)
    low_min, low_max = _oracle_range(summary, low)
    high_min, high_max = _oracle_range(summary, high)
    library_found, library_selected = _family_counts(summary, "library_family")
    drawn_found, drawn_selected = _family_counts(summary, "drawn")
    drawn = next(item for item in summary["planted"] if item["family"] == "drawn")
    runs = summary["runs"]
    planted_runs = [run for run in runs if float(run["snr"]) > 0]
    null_runs = [run for run in runs if float(run["snr"]) == 0]
    markets = _planted_markets(summary)

    def by_snr(level: float, key: str) -> list[float]:
        return [float(market["diagnostics"][key]) for market in markets if float(market["snr"]) == level]

    def span(numbers: list[float], digits: int | None = None) -> str:
        low_value, high_value = min(numbers), max(numbers)
        text = (lambda v: f"{v:g}") if digits is None else (lambda v: fmt(v, digits))
        return text(low_value) if text(low_value) == text(high_value) else f"{text(low_value)}--{text(high_value)}"

    def novelty_span(name: str) -> str:
        return span([float(m["planted_behavioural_novelty"][name]["novelty"]) for m in markets], 2)

    power = [float(m["oracle_test"]["power"]) for m in markets]
    power_low = [float(m["oracle_test"]["power"]) for m in markets if float(m["snr"]) == low]
    software = summary["software"]
    first_complete = next((run for run in planted_runs if run.get("composite_test")), None)
    values = {
        "SynSymbols": str(config["n_symbols"]),
        "SynSessions": str(config["n_dates"]),
        "SynSeeds": str(len(config["seeds"])),
        "SynNullSeeds": str(len(config["null_seeds"])),
        "SynBudget": str(config["budget"]),
        "SynBatch": str(config["batch_size"]),
        "SynTopK": str(config["top_k"]),
        "SynFdrAlpha": f"{float(config['fdr_alpha']):g}",
        "SynConfirmAlpha": f"{float(config['confirm_alpha']):g}",
        "SynMinIcDates": str(config["min_ic_dates"]),
        "SynMinIcFraction": f"{float(config['min_ic_fraction']):g}",
        "SynTestAlpha": f"{float(config['test_alpha']):g}",
        "SynMaxCorr": f"{float(config['max_abs_corr']):g}",
        "SynRecoveryThreshold": f"{float(config['recovery_threshold']):g}",
        "SynTrueDiscoveryThreshold": f"{float(config['true_discovery_threshold']):g}",
        "SynRecallStride": str(config["recall_stride"]),
        "SynSnrLow": f"{low:g}",
        "SynSnrHigh": f"{high:g}",
        "SynOracleLowMin": fmt(low_min, 4),
        "SynOracleLowMax": fmt(low_max, 4),
        "SynOracleHighMin": fmt(high_min, 4),
        "SynOracleHighMax": fmt(high_max, 4),
        "SynPowerLow": span(power_low, 2),
        "SynPowerAll": span(power, 2),
        "SynRuns": str(len(planted_runs)),
        "SynNullRuns": str(len(null_runs)),
        "SynIncompleteRuns": str(len(summary.get("incomplete_runs", []))),
        "SynLibraryFamilyFound": str(library_found),
        "SynLibraryFamilySelected": str(library_selected),
        "SynDrawnFound": str(drawn_found),
        "SynDrawnSelected": str(drawn_selected),
        "SynDrawnName": drawn["name"].replace("_", "\\_"),
        "SynDrawnExpression": "\\texttt{" + drawn["expression"].replace("_", "\\_") + "}",
        "SynNoveltyReversal": novelty_span("reversal_5"),
        "SynNoveltyVolume": novelty_span("abnormal_volume_20"),
        "SynNoveltyLibraryFamily": novelty_span("volume_return_corr_10"),
        "SynNoveltyDrawn": novelty_span(drawn["name"]),
        "SynRuntime": f"{float(summary['runtime_seconds']):g}",
        "SynTestIcDates": str(first_complete["composite_test"]["n_ic_dates"]) if first_complete else "n/a",
        "SynRealizedSnrLow": fmt(sum(by_snr(low, "realized_snr")) / len(by_snr(low, "realized_snr")), 3),
        "SynRealizedSnrHigh": fmt(sum(by_snr(high, "realized_snr")) / len(by_snr(high, "realized_snr")), 3),
        "SynIterationsLow": span(by_snr(low, "iterations")),
        "SynIterationsHigh": span(by_snr(high, "iterations")),
        "SynMaxResidual": latex_scientific(max(float(m["diagnostics"]["residual"]) for m in markets)),
        "SynSoftware": (
            f"Python {software['python']}, numpy {software['numpy']}, pandas {software['pandas']}, "
            f"scipy {software['scipy']}, llm\\_factor\\_mining {software['llm_factor_mining']}"
        ),
    }
    lines = [f"\\newcommand{{\\{name}}}{{{value}}}" for name, value in values.items()]
    return HEADER + "\n".join(lines) + "\n" + LOOKUP_HELPERS + "\n".join(aggregate_macros(summary)) + "\n"


def render(summary: Mapping[str, Any]) -> dict[str, str]:
    """``{file name: LaTeX source}`` for every generated table."""

    return {
        "synthetic_headline.tex": headline_table(summary),
        "synthetic_recovery.tex": recovery_table(summary),
        "synthetic_null.tex": null_table(summary),
        "synthetic_oracle.tex": oracle_table(summary),
        "synthetic_macros.tex": macros(summary),
    }


def stale_tables(summary: Mapping[str, Any], table_dir: Path = TABLE_DIR) -> list[str]:
    """Names of generated tables that are missing or differ from the committed files."""

    stale = []
    for name, text in render(summary).items():
        path = table_dir / name
        if not path.is_file() or path.read_text(encoding="utf-8") != text:
            stale.append(name)
    return stale


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--summary", type=Path, default=SUMMARY)
    parser.add_argument("--out", type=Path, default=TABLE_DIR)
    parser.add_argument("--check", action="store_true", help="fail if committed tables are stale")
    args = parser.parse_args(argv)
    summary = json.loads(args.summary.read_text(encoding="utf-8"))
    if args.check:
        stale = stale_tables(summary, args.out)
        if stale:
            print("stale paper tables: " + ", ".join(stale), file=sys.stderr)
            return 1
        print("paper tables are up to date")
        return 0
    args.out.mkdir(parents=True, exist_ok=True)
    for name, text in render(summary).items():
        (args.out / name).write_text(text, encoding="utf-8")
        print(f"wrote {args.out / name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
