#!/usr/bin/env python3
"""Render the paper's tables and result macros from ``results/benchmark/``.

Every number in ``paper/tables/*.tex`` is produced here from the committed
outputs (``results/benchmark/summary.json`` and ``suite.json``,
``results/verifier/verifier_stress.json`` and ``results/power/power.json``);
none is typed by hand.
The paper cites results only through these files. ``--check`` exits non-zero
when the committed tables are stale, and ``tests/test_docs.py`` runs the same
comparison.

The script uses only the standard library, so the paper can be rebuilt without
the package installed. From the project directory::

    python scripts/render_paper_tables.py            # write paper/tables/*.tex
    python scripts/render_paper_tables.py --check    # fail if they are out of date
"""

from __future__ import annotations

import argparse
from collections.abc import Mapping, Sequence
import json
from pathlib import Path
import re
import sys
from typing import Any


PROJECT = Path(__file__).resolve().parents[1]
RESULTS = PROJECT / "results" / "benchmark"
TABLES = PROJECT / "paper" / "tables"
AGENT_ORDER = ("oracle", "lookahead_naive", "ungrounded", "no_guard", "abstain_or_refuse")
DIGITS = ("Zero", "One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine")
CATEGORY_ORDER = ("lookup", "compute", "multi_step", "pit_trap", "policy_trap", "unknown_symbol")
EXPECTED_LABEL = {"numeric": "numeric", "ranking": "ranking", "abstain": "abstain", "refuse": "refuse"}
RATE_METRICS = {
    "accuracy": "Acc",
    "grounding_rate": "Grounded",
    "citation_rate": "Cited",
    "cited_grounding_rate": "CitedGrounded",
    "fully_grounded_episodes": "FullyGrounded",
    "abstention": "Abstain",
    "false_abstention": "FalseAbstain",
    "over_refusal": "OverRefusal",
    "lookahead_attempt_episodes": "LookaheadEp",
    "lookahead_attempt_episodes_answerable": "LookaheadAnswerableEp",
    "leak_episodes": "LeakEp",
    "denied_call_episodes": "DeniedEp",
    "safety_denial_episodes": "SafetyDeniedEp",
    "order_execution_attempt_episodes": "ExecEp",
    "execution_claim_episodes": "ExecClaimEp",
    "hindsight_match": "Hindsight",
    "hindsight_match_numeric": "HindsightNumeric",
}
CATEGORY_METRICS = {
    "accuracy": "Acc",
    "lookahead_attempt_episodes": "LookaheadEp",
    "leak_episodes": "LeakEp",
    "hindsight_match": "Hindsight",
}
HEADER = (
    "% Generated by scripts/render_paper_tables.py from results/{benchmark,verifier,power}/.\n"
    "% Do not edit by hand. Scripted harness-validation baselines and verifier stress tests on SYNTHETIC data,\n"
    "% and a design-only power analysis; none of these are language-model results.\n"
)
_TEX_SPECIAL = {
    "\\": r"\textbackslash{}",
    "_": r"\_",
    "%": r"\%",
    "&": r"\&",
    "#": r"\#",
    "$": r"\$",
    "{": r"\{",
    "}": r"\}",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
}


def tex(text: Any) -> str:
    """Escape a value for LaTeX text mode."""

    return "".join(_TEX_SPECIAL.get(char, char) for char in str(text))


def camel(name: str) -> str:
    """``lookahead_naive`` -> ``LookaheadNaive``; digits become words (``H3a`` -> ``HThreea``)."""

    spelled = "".join(f"_{DIGITS[int(c)]}_" if c.isdigit() else c for c in str(name))
    return "".join(part[:1].upper() + part[1:] for part in re.split(r"[^A-Za-z]+", spelled) if part)


def rate_word(value: float) -> str:
    """``0.995`` -> ``NineNineFive`` (the digits after the decimal point, spelled)."""

    return "".join(DIGITS[int(c)] for c in f"{value:.3f}".split(".", 1)[1].rstrip("0"))


def pct(value: float | None) -> str:
    return "n/a" if value is None else f"{100.0 * value:.1f}"


def ordered_agents(agents: Mapping[str, Any]) -> list[str]:
    known = [name for name in AGENT_ORDER if name in agents]
    return known + sorted(name for name in agents if name not in AGENT_ORDER)


def load(results: Path) -> tuple[dict[str, Any], dict[str, Any]]:
    summary = json.loads((results / "summary.json").read_text(encoding="utf-8"))
    suite = json.loads((results / "suite.json").read_text(encoding="utf-8"))
    return summary, suite


def load_extra(results: Path) -> tuple[dict[str, Any], dict[str, Any]]:
    """The verifier stress test and the power analysis, next to ``results/benchmark``."""

    root = results.parent
    stress = json.loads((root / "verifier" / "verifier_stress.json").read_text(encoding="utf-8"))
    power = json.loads((root / "power" / "power.json").read_text(encoding="utf-8"))
    return stress, power


def _macro(name: str, value: Any) -> str:
    if not re.fullmatch(r"[A-Za-z]+", name):
        raise ValueError(f"invalid macro name {name!r}")
    return f"\\newcommand{{\\{name}}}{{{value}}}"


def _rate_macros(prefix: str, entry: Mapping[str, Any] | None) -> list[str]:
    entry = entry or {}
    low, high = (entry.get("ci95") or [None, None])[:2]
    return [
        _macro(f"{prefix}K", entry.get("k", "n/a")),
        _macro(f"{prefix}N", entry.get("n", "n/a")),
        _macro(f"{prefix}Pct", pct(entry.get("rate"))),
        _macro(f"{prefix}Lo", pct(low)),
        _macro(f"{prefix}Hi", pct(high)),
    ]


def render_macros(summary: Mapping[str, Any], suite_json: Mapping[str, Any]) -> str:
    suite = summary["suite"]
    dataset = suite["dataset"]
    tasks = suite_json["tasks"]
    as_of_dates = sorted({task["as_of"] for task in tasks})
    answerable = sum(task["expected"]["kind"] in {"numeric", "ranking"} for task in tasks)
    listings = ", ".join(f"{symbol} on {first}" for symbol, first in sorted(dataset["listings"].items()))
    env = summary["environment"]
    lines = [
        HEADER.rstrip("\n"),
        _macro("resBanner", tex(summary.get("banner") or "")),
        _macro("SuiteTasks", suite["n_tasks"]),
        _macro("SuiteDistinctItems", suite["distinct_items"]),
        _macro("SuiteSeed", suite["seed"]),
        _macro("SuiteShort", suite["sha256"][:16]),
        _macro("SuiteGenerator", tex(suite["generator_version"])),
        _macro("SuiteAnswerable", answerable),
        _macro("SuiteHindsightTasks", sum(task["hindsight"] is not None for task in tasks)),
        _macro("SuiteHindsightDropped", sum(bool(task["metadata"].get("hindsight_equals_truth")) for task in tasks)),
        _macro("SuiteAsOfDates", len(as_of_dates)),
        _macro("SuiteAsOfFirst", as_of_dates[0]),
        _macro("SuiteAsOfLast", as_of_dates[-1]),
    ]
    for category, count in suite["counts"].items():
        lines.append(_macro(f"SuiteCat{camel(category)}", count))
    subcategories: dict[str, int] = {}
    for task in tasks:
        subcategories[task["subcategory"]] = subcategories.get(task["subcategory"], 0) + 1
    for subcategory, count in sorted(subcategories.items()):
        lines.append(_macro(f"SuiteSub{camel(subcategory)}", count))
    lines += [
        _macro("DataSymbols", len(dataset["symbols"])),
        _macro("DataStart", dataset["start"]),
        _macro("DataEnd", dataset["end"]),
        _macro("DataSeed", dataset["seed"]),
        _macro("DataMarketVol", dataset["market_vol"]),
        _macro("DataIdioVol", dataset["idio_vol"]),
        _macro("DataListings", tex(listings)),
        _macro("RunMaxSteps", summary["max_steps"]),
        _macro("RunPrompt", tex(summary["prompt_version"])),
        _macro("EnvPython", tex(env["python"])),
        _macro("EnvNumpy", tex(env["numpy"])),
        _macro("EnvPandas", tex(env["pandas"])),
        _macro("EnvPackage", tex(env["marketdata_agent"])),
    ]
    for name in ordered_agents(summary["agents"]):
        agent = summary["agents"][name]
        overall = agent["overall"]
        prefix = f"res{camel(name)}"
        for key, suffix in RATE_METRICS.items():
            lines += _rate_macros(prefix + suffix, overall.get(key))
        lines += [
            _macro(f"{prefix}LookaheadCalls", overall["lookahead_attempts"]),
            _macro(f"{prefix}UnknownCitations", overall["unknown_citations"]),
            _macro(f"{prefix}ToolCalls", f"{overall['mean_tool_calls']:.2f}"),
            _macro(f"{prefix}Steps", f"{overall['mean_steps']:.2f}"),
            _macro(f"{prefix}AuditRecords", agent["audit"]["records"]),
            _macro(f"{prefix}AuditHead", agent["audit"]["head_hash"][:16]),
            _macro(f"{prefix}AuditOk", "verified" if agent["audit"]["ok"] else "FAILED"),
            _macro(f"{prefix}Clock", "on" if agent["clock_enforced"] else "off"),
            _macro(f"{prefix}EpisodesSha", agent["episodes_sha256"][:16]),
        ]
        for category, metrics in agent["by_category"].items():
            for key, suffix in CATEGORY_METRICS.items():
                entry = metrics.get(key) or {}
                lines.append(_macro(f"{prefix}Cat{camel(category)}{suffix}K", entry.get("k", "n/a")))
                lines.append(_macro(f"{prefix}Cat{camel(category)}{suffix}N", entry.get("n", "n/a")))
    return "\n".join(lines) + "\n"


def render_extra_macros(stress: Mapping[str, Any], power: Mapping[str, Any]) -> str:
    """Macros for the verifier stress test (``ver...``) and the power analysis (``pow...``)."""

    lines = [HEADER.rstrip("\n")]
    injections = stress["oracle_injections"]
    lines.append(_macro("verEpisodes", injections["episodes_with_results"]))
    lines.append(_macro("verSamples", injections["samples_per_episode"]))
    for row in stress["ungrounded_by_mode"]:
        prefix = f"verUngrounded{camel(row['mode'])}"
        lines += [_macro(f"{prefix}Claims", row["claims"]), _macro(f"{prefix}Accepted", row["accepted"])]
        lines += [_macro(f"{prefix}Episodes", row["episodes"]), _macro(f"{prefix}WithResults", row["episodes_with_results"])]
        lines.append(_macro(f"{prefix}Correct", row["correct"]))
    for cell in injections["cells"]:
        prefix = f"ver{camel(cell['mode'])}{camel(cell['unit'])}{DIGITS[int(cell['decimals'])]}"
        lines += _rate_macros(prefix, cell)
    for row in injections["by_outputs"]:
        bucket = {"1-5": "Few", "6-20": "Some", "21+": "Many"}[row["outputs_in_episode"]]
        lines += _rate_macros(f"ver{camel(row['mode'])}Outputs{bucket}", row)
    design = power["design"]
    lines += [
        _macro("powSuites", design["evaluation_suites"]),
        _macro("powRepetitions", design["repetitions"]),
        _macro("powTasksPerSuite", design["tasks_per_suite"]),
        _macro("powEpisodes", design["main_episodes"]),
        _macro("powSweepSuites", design["sweep_suites"]),
        _macro("powSweepItems", design["sweep_answerable_items"]),
    ]
    for name, family in power["families"].items():
        lines.append(_macro(f"powItems{camel(name)}", family["distinct_items"]))
        lines.append(_macro(f"powClusters{camel(name)}", family["clusters"]))
    for hyp in power["hypotheses"]:
        prefix = f"pow{camel(hyp['id'])}"
        allowed = hyp["failures_allowed"]
        lines.append(_macro(f"{prefix}Allowed", "none" if allowed is None else allowed))
        for row in hyp["power"]:
            for mode in ("independent", "identical"):
                lines.append(_macro(f"{prefix}{camel(mode)}{rate_word(row['rate'])}", f"{row[mode]:.2f}"))
            for key in sorted(k for k in row if k.startswith("clustered_icc_")):
                icc = float(key.rsplit("_", 1)[1])
                lines.append(_macro(f"{prefix}Icc{rate_word(icc)}{rate_word(row['rate'])}", f"{row[key]:.2f}"))
    lines.append(_macro("powMaxClusterShift", f"{power['largest_cluster_shift']['shift']:.2f}"))
    for row in power["noninferiority"]:
        lines.append(
            _macro(f"powNonInf{rate_word(row['discordance'])}Margin{rate_word(row['margin'])}", row["items_needed"])
        )
    return "\n".join(lines) + "\n"


def _kn(entry: Mapping[str, Any] | None) -> str:
    if not entry or entry.get("n") in (None, 0):
        return "n/a"
    return f"{entry['k']}/{entry['n']}"


def _ci(entry: Mapping[str, Any]) -> str:
    low, high = entry["ci95"]
    if entry.get("rate") is None:
        return "n/a"
    return f"{pct(entry['rate'])} [{pct(low)}, {pct(high)}]"


def _tabular(spec: str, header: Sequence[str], rows: Sequence[Sequence[str]], groups: Sequence[int] = ()) -> str:
    lines = [HEADER.rstrip("\n"), f"\\begin{{tabular}}{{{spec}}}", "\\toprule", " & ".join(header) + " \\\\", "\\midrule"]
    for index, row in enumerate(rows):
        if index in groups and index != 0:
            lines.append("\\midrule")
        lines.append(" & ".join(row) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


def render_baselines(summary: Mapping[str, Any]) -> str:
    header = (
        "Agent",
        "Clock",
        "Accuracy, \\% [95\\% CI]",
        "Grounded claims",
        "Cited claims",
        "Look-ahead ep.",
        "Leak ep.",
        "Safety-denial ep.",
        "Execution-attempt ep.",
        "False abstention",
        "Hindsight match (numeric)",
    )
    rows = []
    for name in ordered_agents(summary["agents"]):
        agent = summary["agents"][name]
        o = agent["overall"]
        rows.append(
            [
                f"\\texttt{{{tex(name)}}}",
                "on" if agent["clock_enforced"] else "off",
                _ci(o["accuracy"]),
                _kn(o["grounding_rate"]),
                _kn(o["citation_rate"]),
                _kn(o["lookahead_attempt_episodes"]),
                _kn(o["leak_episodes"]),
                _kn(o["safety_denial_episodes"]),
                _kn(o["order_execution_attempt_episodes"]),
                _kn(o["false_abstention"]),
                _kn(o["hindsight_match_numeric"]),
            ]
        )
    return _tabular("llccccccccc", header, rows)


def render_categories(summary: Mapping[str, Any]) -> str:
    names = ordered_agents(summary["agents"])
    header = ["Category", "Tasks", *[f"\\texttt{{{tex(name)}}}" for name in names]]
    rows = []
    for category in CATEGORY_ORDER:
        entries = [summary["agents"][name]["by_category"].get(category) for name in names]
        if not any(entries):
            continue
        n = next(entry["accuracy"]["n"] for entry in entries if entry)
        rows.append(
            [f"\\texttt{{{tex(category)}}}", str(n), *[str(entry["accuracy"]["k"]) if entry else "n/a" for entry in entries]]
        )
    return _tabular("lr" + "r" * len(names), header, rows)


def render_suite(suite_json: Mapping[str, Any]) -> str:
    groups: dict[tuple[str, str], list[Mapping[str, Any]]] = {}
    for task in suite_json["tasks"]:
        groups.setdefault((task["category"], task["subcategory"]), []).append(task)
    rows: list[list[str]] = []
    starts: list[int] = []
    for category in CATEGORY_ORDER:
        keys = [key for key in groups if key[0] == category]
        if keys:
            starts.append(len(rows))
        for key in keys:
            items = groups[key]
            kinds = sorted({EXPECTED_LABEL[item["expected"]["kind"]] for item in items})
            rows.append(
                [
                    f"\\texttt{{{tex(category)}}}" if key == keys[0] else "",
                    f"\\texttt{{{tex(key[1])}}}",
                    str(len(items)),
                    ", ".join(kinds),
                    str(sum(item["hindsight"] is not None for item in items)),
                ]
            )
    header = ("Category", "Subcategory", "Tasks", "Expected", "With hindsight value")
    return _tabular("llrlr", header, rows, groups=starts)


def render_verifier(stress: Mapping[str, Any]) -> str:
    header = ("Mode", "Episodes", "With tool results", "Claims", "Accepted")
    rows = [
        [f"\\texttt{{{tex(row['mode'])}}}", str(row["episodes"]), str(row["episodes_with_results"]), str(row["claims"]), str(row["accepted"])]
        for row in stress["ungrounded_by_mode"]
    ]
    return _tabular("lrrrr", header, rows)


def render_injections(stress: Mapping[str, Any]) -> str:
    header = ("Injected claim", "Unit", "Decimals", "Accepted / injected", "False acceptance, \\% [95\\% CI]")
    rows = [
        [f"\\texttt{{{tex(cell['mode'])}}}", tex(cell["unit"]), str(cell["decimals"]), _kn(cell), _ci(cell)]
        for cell in stress["oracle_injections"]["cells"]
    ]
    return _tabular("llrrr", header, rows)


def render_power(power: Mapping[str, Any]) -> str:
    header = ("Hypothesis", "Threshold", "Items", "Clusters", "Failures allowed", "$p$", "Indep.", "Identical")
    rows = []
    for hyp in power["hypotheses"]:
        family = power["families"][hyp["family"]]
        bound = ("$\\ge$ " if hyp["direction"] == "at_least" else "$\\le$ ") + f"{100 * hyp['threshold']:.0f}\\%"
        allowed = "none" if hyp["failures_allowed"] is None else str(hyp["failures_allowed"])
        for index, row in enumerate(hyp["power"]):
            first = index == 0
            rows.append(
                [
                    tex(hyp["id"]) if first else "",
                    bound if first else "",
                    str(hyp["distinct_items"]) if first else "",
                    str(family["clusters"]) if first else "",
                    allowed if first else "",
                    str(row["rate"]),
                    f"{row['independent']:.2f}",
                    f"{row['identical']:.2f}",
                ]
            )
    starts = []
    count = 0
    for hyp in power["hypotheses"]:
        starts.append(count)
        count += len(hyp["power"])
    return _tabular("llrrrrrr", header, rows, groups=starts)


def render_all(results: Path = RESULTS) -> dict[str, str]:
    """Return ``{file name: content}`` for every generated table."""

    summary, suite_json = load(results)
    stress, power = load_extra(results)
    return {
        "macros.tex": render_macros(summary, suite_json) + render_extra_macros(stress, power),
        "baselines.tex": render_baselines(summary),
        "categories.tex": render_categories(summary),
        "suite.tex": render_suite(suite_json),
        "verifier.tex": render_verifier(stress),
        "injections.tex": render_injections(stress),
        "power.tex": render_power(power),
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--results", default=str(RESULTS), help="benchmark results directory")
    parser.add_argument("--out", default=str(TABLES), help="output directory for the .tex tables")
    parser.add_argument("--check", action="store_true", help="exit 1 if the committed tables are stale")
    args = parser.parse_args(argv)
    rendered = render_all(Path(args.results))
    out = Path(args.out)
    stale = [name for name, text in rendered.items() if not (out / name).is_file() or (out / name).read_text(encoding="utf-8") != text]
    if args.check:
        for name in stale:
            print(f"stale: {out / name}", file=sys.stderr)
        print("paper tables are up to date" if not stale else f"{len(stale)} stale table(s); rerun without --check")
        return 1 if stale else 0
    out.mkdir(parents=True, exist_ok=True)
    for name, text in rendered.items():
        (out / name).write_text(text, encoding="utf-8")
    print(f"wrote {len(rendered)} tables to {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
